const desmembraFII = new Object()
desmembraFII.proventos = await fiis[0]
desmembraFII.codigoIsin = await fiis[1]
desmembraFII.deliberadoEm = await fiis[2]
desmembraFII.negociosComAte = await fiis[3]
desmembraFII.valor = await fiis[4]
desmembraFII.RelativoA = await fiis[5]
desmembraFII.inicioDePagamento = await fiis[6]
desmembraFII.observacoes = await fiis[7]